timezone: Asia/Calcutta
# Dependencies
markdown:       kramdown
redcarpet:
    extensions: ['smart']

highlighter:         rouge
fenced_code_blocks:  true

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:            Invisible Shackles
tagline:          Thoughts on oxymorones in life
url:              http://jaleyhd.github.io
paginate:            5
baseurl:          /

# About/contact
author:
  name:           Jaley Dholakiya
  url:            http://jaleyhd.github.io
  email:          jaley.dholakiya@gmail.com
